logging:
  level:
    org.springframework.security: trace
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: trace


spring:
  security:
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              client-id: "desktop-client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://127.0.0.1:8080/desktop/authorized"
              post-logout-redirect-uris:
                - "http://127.0.0.1:8080/desktop/logged-out"
              scopes:
                - "openid"
            require-authorization-consent: true
            require-proof-key: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: private_password