logging:
  level:
    org.springframework.security: trace
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: trace
server:
  port: 6543
  servlet:
    session:
      timeout: 10s

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: private_password
  session:
    timeout: 10s