apiVersion: v1
kind: Service
metadata:
  name: gateway
  annotations:
    owner: kyamshanov
    description: Backend gateway Service
spec:
  type: LoadBalancer
  selector:
    app: backend-gateway-deployment
  ports:
    - name: backend-gateway-port
      protocol: TCP
      port: 3456
      targetPort: gateway-https