apiVersion: v1
kind: Service
metadata:
  name: point
  annotations:
    owner: kyamshanov
    description: Backend Point Service http
spec:
  type: ClusterIP
  selector:
    app: backend-point-deployment
  ports:
    - name: point-http-port
      protocol: TCP
      port: 80
      targetPort: point-http