apiVersion: v1
kind: PersistentVolume
metadata:
  name: p-d-pv
spec:
  local:
    path: ${REALPATH_ASSETS}/db_data/postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - kind-control-plane