apiVersion: v1
kind: PersistentVolume
metadata:
  name: p-is-pv
spec:
  local:
    path: ${REALPATH_ASSETS}/init_db
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ${HOSTNAME}