server:
  port: 80

logging.level:
  org.springframework.cloud.gateway: TRACE
  org.springframework.security: TRACE
  org.springframework.web.reactive.function.client: TRACE

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
  cloud:
    gateway:
      routes:
        - id: resource
          uri: http://resource:9000
          predicates:
            - Path=/resource
          filters:
            - RemoveRequestHeader=Cookie