logging.level:
  org.springframework.cloud.gateway: TRACE
  org.springframework.security: TRACE
  org.springframework.web.reactive.function.client: TRACE

server:
  port: 443
  ssl:
    enabled: true
    key-alias: ${cipher_keyAlias}
    key-store-password: ${cipher_keyStorePassword}
    key-store: ${cipher_keyStore}
    key-store-type: JKS
    key-password: ${cipher_keyPassword}

spring:
  config:
    import: 'optional:configtree:/run/secrets/'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
      routes:
        - id: point
          uri: http://point:80
          predicates:
            - Path=/point/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: oauth
          uri: http://auth:80
          predicates:
            - Path=/oauth2/**