apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: p-d-pvc
  annotations:
    owner: kyamshanov
    description: Postgres Data Persistent Volume Claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 20Gi