apiVersion: v1
kind: PersistentVolume
metadata:
  name: p-d-pv
  annotations:
    owner: kyamshanov
    description: Postgres Data Persistent Volume - local storage
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: ../../assets/db_data/postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - docker-desktop