apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: p-is-pvc
  annotations:
    owner: kyamshanov
    description: Postgres Init Scripts Persistent Volume Claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi