apiVersion: v1
kind: PersistentVolume
metadata:
  name: p-is-pv
  annotations:
    owner: kyamshanov
    description: Postgres Init Scripts Persistent Volume - local storage
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: ../../assets/init_db
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - docker-desktop