apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - database-pv.yaml
  - init-db-pv.yaml
  - database-pvc.yaml
  - init-db-pvc.yaml

secretGenerator:
  - name: postgres-secret
    files:
      - secrets/postgres_db
      - secrets/postgres_password
      - secrets/postgres_user