apiVersion: v1
kind: Service
metadata:
  name: postgres
  annotations:
    owner: kyamshanov
    description: Postgres Service
spec:
  selector:
    app: postgres-deployment
  ports:
    - name: postgres-access-port
      protocol: TCP
      port: 5432
      targetPort: postgres-port