version: '3.9'

services:
  postgres:
    image: postgres:14
    container_name: 'postgres'
    environment:
      POSTGRES_DB_FILE: /run/secrets/postgres_db
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ${assets}/init_db:/docker-entrypoint-initdb.d
      - ${assets}/db_data/postgres:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5431:5432"
    networks:
      - postgres
    restart: always
    secrets:
      - postgres_db
      - postgres_user
      - postgres_password

networks:
  postgres:
    driver: overlay
    driver_opts:
      com.docker.network.driver.mtu: 1450
    attachable: true

secrets:
  postgres_db:
    file: postgres_db.txt
  postgres_user:
    file: postgres_user.txt
  postgres_password:
    file: postgres_password.txt