version: '1.0'

services:
  auth:
    build: ../id
    container_name: 'auth'
    networks:
      - auth-server
      - database_postgres
      - gateway
    volumes:
      - ./../id/GeneratorSslKeys/build/certs/:/certs
    ports:
      - 6543:443
    environment:
      SERVER_PORT: 80
      clientId: ${clientId}
      clientSecret: ${clientSecret}
      postgresql_url: 'jdbc:postgresql://postgres:5432/postgres'
      keyStore: '/certs/keystore.jks'
      keyAlias: ${keyAlias}
      keyStorePassword: ${keyStorePassword}
      privateKeyPassword: ${privateKeyPassword}
      tokenKeyStore: '/certs/tokenkeystore.jks'
      tokenKeyAlias: ${tokenKeyAlias}
      tokenKeyStorePassword: ${keyStorePassword}
      tokenKeyPassword: ${tokenKeyPassword}
      SSL_PORT: 443
      githubUrlProvider: ${githubUrlProvider}
      postgresql_user: ${postgresql_user}
      postgresql_password: ${postgresql_password}
  gateway:
    build: ../gateway
    container_name: 'gateway'
    ports:
      - 3456:443
    networks:
      - gateway
      - auth-server
    volumes:
      - ./../id/GeneratorSslKeys/build/certs/:/certs
    environment:
      SERVER_PORT: 443
      keyStore: '/certs/keystore.jks'
      keyAlias: ${keyAlias}
      keyStorePassword: ${keyStorePassword}
      privateKeyPassword: ${privateKeyPassword}
      SSL_PORT: 443
  point:
    build: ../point
    container_name: 'point'
    networks:
      - database_postgres
      - backend
      - gateway
    environment:
      SERVER_PORT: 80
      postgresql_url_r2dbc: 'r2dbc:postgresql://postgres:5432/postgres'
      postgresql_user: ${postgresql_user}
      postgresql_password: ${postgresql_password}
    ports:
      - 8081:80
networks:
  database_postgres:
    name: database_postgres
    external: true
  database_mongo:
    name: database_mongo
    external: true
  gateway:
    driver: bridge
    name: gateway
  backend:
    driver: bridge
    name: backend
  auth-server:
    driver: bridge
    name: auth-server
  hostnet:
    external:
      name: host