version: '1.0'

services:
  auth:
    build: ../id
    container_name: 'auth'
    networks:
      - auth-server
      - database_postgres
      - gateway
    ports:
      - 6543:80
    environment:
      SERVER_PORT: 80
      clientId: ${clientId}
      clientSecret: ${clientSecret}
      postgresql_url: 'jdbc:postgresql://postgres:5432/postgres'
  gateway:
    build: ../gateway
    container_name: 'gateway'
    ports:
      - 3456:80
    networks:
      - gateway
      - auth-server
    volumes:
      - ./assets:/app/assets
    environment:
      SERVER_PORT: 80
  point:
    build: ../point
    container_name: 'point'
    networks:
      - database_postgres
      - backend
      - gateway
    environment:
      SERVER_PORT: 80
      postgresql_url: 'r2dbc:postgresql://postgres:5432/postgres'
    ports:
      - 8081:80
networks:
  database_postgres:
    name: database_postgres
    external: true
  database_mongo:
    name: database_mongo
    external: true
  gateway:
    driver: bridge
    name: gateway
  backend:
    driver: bridge
    name: backend
  auth-server:
    driver: bridge
    name: auth-server
  hostnet:
    external:
      name: host