ktor:
  deployment:
    port: 80
    sslPort: 443
  security:
    ssl:
      keyStore: "$keyStore:SECRET_ssl_keyStore"
      keyAlias: "$keyAlias:SECRET_ssl_keyAlias"
      keyStorePassword: "$keyStorePassword:SECRET_ssl_keyStorePassword"
      privateKeyPassword: "$privateKeyPassword:SECRET_ssl_keyPassword"
  application:
    modules:
      - ru.kyamshanov.mission.ApplicationKt.module
oauth:
  issuer: "http://auth"
  security:
    cipher:
      keyAlias: "$tokenKeyAlias:SECRET_cipher_keyAlias"
      keyPassword: "$tokenKeyPassword:SECRET_cipher_keyPassword"
      keyStore: "$tokenKeyStore:SECRET_cipher_keyStore"
      keyStorePassword: "$tokenKeyStorePassword:SECRET_cipher_keyStorePassword"
  github:
    urlProvider: "$githubUrlProvider:SECRET_github_urlProvider"
    clientId: "$clientId:SECRET_github_clientId"
    clientSecret: "$clientSecret:SECRET_github_clientSecret"
database:
  postgresql:
    url: "$postgresql_url:SECRET_postgresql_url"
    user: "$postgresql_user:SECRET_postgresql_user"
    password: "$postgresql_password:SECRET_postgresql_password"
