ktor:
  deployment:
    port: $SERVER_PORT
    sslPort: $SSL_PORT
  security:
    ssl:
      keyStore: $keyStore
      keyAlias: $keyAlias
      keyStorePassword: $keyStorePassword
      privateKeyPassword: $privateKeyPassword
  application:
    modules:
      - ru.kyamshanov.mission.ApplicationKt.module
oauth:
  issuer: "http://auth"
  github:
    urlProvider: "http://127.0.0.1:6543/github/authorized"
    clientId: $clientId
    clientSecret: $clientSecret
database:
  postgresql:
    url: $postgresql_url
    user: postgres
    password: private_password
